<a href="https://colab.research.google.com/github/ayatayoub20/intermediate-machine-learning-projects/blob/main/Dimensionality_Reduction/Feature_Engineering_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Imports

In [38]:
# Imports
import numpy as np
import pandas as pd

pd.set_option('display.max_columns',100)

##2. Load the Data

In [25]:
df = pd.read_csv("/content/drive/MyDrive/AXSOSACADEMY/03-DataEnrichment/Week09/Data/bikeshare_train - bikeshare_train.csv")
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   datetime    10886 non-null  object
 1   season      10886 non-null  int64
 2   holiday     10886 non-null  int64
 3   workingday  10886 non-null  int64
 4   weather     10886 non-null  int64
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64
 10  registered  10886 non-null  int64
 11  count       10886 non-null  int64
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,casual,registered,count
0,2011-01-01 0:00:00,1,0,0,1,9.84,14.395,81,0.0,3,13,16
1,2011-01-01 1:00:00,1,0,0,1,9.02,13.635,80,0.0,8,32,40
2,2011-01-01 2:00:00,1,0,0,1,9.02,13.635,80,0.0,5,27,32
3,2011-01-01 3:00:00,1,0,0,1,9.84,14.395,75,0.0,3,10,13
4,2011-01-01 4:00:00,1,0,0,1,9.84,14.395,75,0.0,0,1,1

##3. Drop Redundant Columns

In [26]:
df.drop(columns=['casual', 'registered'], inplace=True)

##4. Convert Datetime Column

In [27]:
df['datetime'] = pd.to_datetime(df['datetime'])

##5. Create New Datetime Features

In [ ]:
df['month'] = df['datetime'].dt.month_name()
df['day'] = df['datetime'].dt.day_name()
df['hour'] = df['datetime'].dt.hour

In [28]:
df.head()

,datetime,season,holiday,workingday,weather,temp,atemp,humidity,windspeed,count,month,day,hour
0,2011-01-01 00:00:00,1,0,0,1,9.84,14.395,81,0.0,16,January,Saturday,0
1,2011-01-01 01:00:00,1,0,0,1,9.02,13.635,80,0.0,40,January,Saturday,1
2,2011-01-01 02:00:00,1,0,0,1,9.02,13.635,80,0.0,32,January,Saturday,2
3,2011-01-01 03:00:00,1,0,0,1,9.84,14.395,75,0.0,13,January,Saturday,3
4,2011-01-01 04:00:00,1,0,0,1,9.84,14.395,75,0.0,1,January,Saturday,4

##6. Convert New Columns to Object Type

In [29]:
df.dtypes

datetime      datetime64[ns]
season                 int64
holiday                int64
workingday             int64
weather                int64
temp                 float64
atemp                float64
humidity               int64
windspeed            float64
count                  int64
month                 object
day                   object
hour                   int32
dtype: object

In [30]:
df['hour'] = df['hour'].astype('object')

In [31]:
df.dtypes

datetime      datetime64[ns]
season                 int64
holiday                int64
workingday             int64
weather                int64
temp                 float64
atemp                float64
humidity               int64
windspeed            float64
count                  int64
month                 object
day                   object
hour                  object
dtype: object

##7. Drop Redundant Columns

In [32]:
df.drop(columns=['datetime', 'season'], inplace=True)

##8. Convert Celsius to Fahrenheit Using apply + lambda

In [33]:
df['temp'] = df['temp'].apply(
    lambda x: (x * 9/5) + 32
)

In [34]:
df['atemp'] = df['atemp'].apply(
    lambda x: (x * 9/5) + 32
)

##9. Create temp_variance Feature

In [35]:
df['temp_variance'] = df['temp'] - df['atemp']

In [36]:
df.drop(columns='atemp', inplace=True)

In [37]:
df.head()

,holiday,workingday,weather,temp,humidity,windspeed,count,month,day,hour,temp_variance
0,0,0,1,49.712,81,0.0,16,January,Saturday,0,-8.199
1,0,0,1,48.236,80,0.0,40,January,Saturday,1,-8.307
2,0,0,1,48.236,80,0.0,32,January,Saturday,2,-8.307
3,0,0,1,49.712,75,0.0,13,January,Saturday,3,-8.199
4,0,0,1,49.712,75,0.0,1,January,Saturday,4,-8.199

# Feature Engineering Summary

Several new features were engineered from the original dataset to improve the model’s ability to predict hourly bike-share rentals.

The `datetime` column was converted into a datetime datatype, and new features were extracted from it, including:
- Month name
- Day name
- Hour of the day

These features may help the model detect seasonal and hourly rental patterns.

The temperature-related columns (`temp` and `atemp`) were converted from Celsius to Fahrenheit using `.apply()` with lambda functions.

A new feature called `temp_variance` was also created to measure how much warmer or colder the actual temperature was compared to the “feels like” temperature.

Finally, redundant columns such as `datetime`, `season`, and `atemp` were removed.